ServerRoot "/opt/apache-2.2"
Listen 80
ServerName localhost

LoadModule rewrite_module modules/mod_rewrite.so
LoadModule headers_module modules/mod_headers.so
LoadModule php5_module modules/libphp5.so

User www-data
Group www-data
ServerAdmin webmaster@localhost

DocumentRoot "/var/www/html"
<Directory "/var/www/html">
    Options Indexes FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

DirectoryIndex index.php index.html

AddType application/x-httpd-php .php

ErrorLog logs/error.log
LogLevel warn
CustomLog logs/access.log combined
